// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-jP9IeeDzzNdp5e8xhvwTLDpqzPXiIy4',
    appId: '1:437328648468:web:0b05f5ed873cf7874a8a01',
    messagingSenderId: '437328648468',
    projectId: 'micromentor-946f9',
    authDomain: 'micromentor-946f9.firebaseapp.com',
    databaseURL: 'https://micromentor-946f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'micromentor-946f9.firebasestorage.app',
    measurementId: 'G-4W4EE0VXST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyx9WhSYBNvXiWwt_uFjgb_yEeum7vZD8',
    appId: '1:437328648468:android:aeb141eb1e6006fa4a8a01',
    messagingSenderId: '437328648468',
    projectId: 'micromentor-946f9',
    databaseURL: 'https://micromentor-946f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'micromentor-946f9.firebasestorage.app',
  );
}
